services:

  api:
    build:
      context: ./backend/app
      dockerfile: docker/api/Dockerfile
    
    environment:
      - API_REDIS_HOST=redis
    ports:
      - 8000:8000
    command: [
      "uvicorn", "app:app",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]

    depends_on:
      - redis

  redis:
    container_name: redis
    build:
      context: ./backend/app
      dockerfile: docker/redis/Dockerfile
    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    ports:
      - 6379:6379
      