services:

  api:
    build:
      context: ./backend/app
    environment:
      - API_REDIS_HOST=redis
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6379:6379